export { ParquesComponent } from "./parques/parques.component";
export { TiendaComponent } from "./tienda/tienda.component";
export { AnimalsComponent } from "./animals/animals.component";
export { ContactComponent } from "./contact/contact.component";
export { HomeComponent } from "./home/home.component";
export { KeeperComponent } from "./keeper/keeper.component";
export { LoginComponent } from "./login/login.component";
export { RegisterComponent } from "./register/register.component";
export { UserEditComponent } from "./user-edit/user-edit.component";
